blank_issues_enabled: false
contact_links:
  - name: General Question
    url: https://discord.alternerd.tv
    about: Please ask general support questions in the appropriate channel in Discord instead of filing an issue.
